title: Freedman Test Site
description: This is a Test
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
<h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
<h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>

